#!/bin/sh

cd `dirname $0`


CLASSPATH=lib:lib/filedrop.jar:lib/j3dcore.jar:lib/j3dutils.jar:lib/jcommon-1.0.16.jar:lib/miglayout-3.7.4.jar:lib/mrj.jar:lib/quaqua.jar:lib/vecmath.jar:lib/commons-lang3-3.1.jar:lib/usb-api-1.0.2.jar:lib/usb4java-1.0.0.jar:lib/BEESOFT.jar:lib/OrangeExtensions-1.2.jar
export CLASSPATH

export PATH

MACHINE=`uname -m`

# put the directory with the native RXTX libs in the library path
LD_LIBRARY_PATH=`pwd`/lib-${MACHINE}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

if [ ${http_proxy} ]; then
  PROXY=`echo -n -e ${http_proxy} | sed -n 's/http:\/\/\([^:]\+\):\([1234567890]\+\)/-DproxySet=true -DproxyHost=\1 -DproxyPort=\2/p'`
  java -Xms1024m -Xmx2048m $PROXY replicatorg.app.Base "$@"
else
  java -Xms1024m -Xmx2048m replicatorg.app.Base "$@"
fi
